server:
  port: 8091

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
  datasource:
    url: jdbc:postgresql://localhost:5433/Database2
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      format_sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

